name: demo_project_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  shared_preferences: ^2.0.12
  intl: ^0.17.0
  get: ^4.6.1
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_staggered_animations: ^1.0.0
  skeletons: ^0.0.3
  flutter_svg: ^1.0.3
  flutter_rating_bar: ^4.0.0
  dotted_decoration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  remove_alpha_ios: true



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

